
kind: secret
name: mysql_user
---
kind: secret
name: mysql_password
---
kind: secret
name: docker_user
---
kind: secret
name: docker_password
---
kind: secret
name: cluster_url
---
kind: secret
name: cluster_token
---
kind: pipeline
type: kubernetes
name: Test

steps:
- name: Run test
  image: maven:3.6.3-jdk-11
  environment:
    MYSQL_USER:
      from_secret:
        mysql_user
    MYSQL_PASSWORD:
      from_secret:
        mysql_password
  commands:
    - mvn test

trigger:
  branch:
    - master
    - beta
    - dev
    - tdcc-demo

---
kind: pipeline
type: kubernetes
name: Publish

steps:
- name: Build Jar
  image: maven:3.6.3-jdk-11
  commands:
    - mvn install -DskipTests
    - mvn package spring-boot:repackage
- name: Publish Docker Image
  image: plugins/docker
  settings:
    repo: ssl1321ois/timelog_server
    tags:
      ${DRONE_COMMIT_BRANCH}.${DRONE_COMMIT_SHA:0:8}
    username:
      from_secret:
        docker_user
    password:
      from_secret:
        docker_password

trigger:
  branch:
    - master
    - beta
    - tdcc-demo
  event:
    - push

depends_on:
  - Test

---
kind: pipeline
type: kubernetes
name: Deployment

steps:
- name: Deploy Demo
  image: nightlord851108/kustomize
  environment:
    KUBE_CLUSTER_URL:
      from_secret:
        cluster_url
    CLUSTER_TOKEN:
      from_secret:
        cluster_token
  commands:
    - cd kustomize/overlays/demo
    - kustomize edit set image ssl1321ois/timelog_server:${DRONE_COMMIT_BRANCH}.${DRONE_COMMIT_SHA:0:8}
    - kustomize build . | kubectl apply --server=$${KUBE_CLUSTER_URL}  --token=$${CLUSTER_TOKEN} --insecure-skip-tls-verify=true --namespace=ois-demo -f -
  when:
    branch:
      - tdcc-demo
    event:
      - push

depends_on:
  - Publish
trigger:
  branch:
    - tdcc-demo
